In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list =[[1,2],[3,4]]
np.array(nested_list)

array([[1, 2],
       [3, 4]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# make an array with a certain quantity of points between them
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [14]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand()

0.7201164408723626

In [23]:
np.random.rand(10)

array([0.15784191, 0.41824353, 0.48967044, 0.3843603 , 0.19139995,
       0.88443922, 0.81094021, 0.63352715, 0.33320202, 0.57408194])

In [28]:
np.random.rand(3, 2)

array([[0.60103124, 0.65621193],
       [0.69363266, 0.80355404],
       [0.0557352 , 0.45757603]])

In [29]:
np.random.randn()

-1.231781361950549

In [34]:
np.random.randn(3,2)

array([[-1.24386958,  0.3852849 ],
       [-0.38990428, -0.13981048],
       [ 0.59717406,  0.29236926]])